### PR TITLE
Add link to discourse forum to doc

### PR DESCRIPTION
**Pull request by pieper**

### CODE REVIEW

**Comment by tkoyama010** [comment]
@pieper Thank you for your contribution. This is a great change, but unfortunately, this repository is a mirror repository, Could you please follow the [How to contribute / Git repository on Savannah](https://getfem.org/project/contribute.html) procedure and propose this change? If you have any clarifications, please ask.

**Comment by pieper** [comment]
> this repository is a mirror repository

Ah, of course, sorry I didn't see that!

**Comment by logari81** [comment]
I have now pushed a modified version of this PR to the main GetFEM repo. Thanks for the suggestions.

**Comment by pieper** [comment]
> I have now pushed a modified version of this PR to the main GetFEM repo. Thanks for the suggestions.

Thanks 👍  I've been going through the process of getting signed up on savannah, but there were several steps and I'd never done it before.

**Pull request closed without merging**
